// Command eloctaedro answers the captain's projection question.
//
// HIS FLASH: "that is a circle and ONE radius - but what happens when you
// project it to ALL the radii, in every direction, and instead of a circle it
// is a SPHERE with the 6 cardinal points we named before? What FORM do they
// obtain, what SENSE do they have, what do they PROJECT?"
//
// The answer has a name, and everything below is computed.
//
// THE SPHERE. The disk of dimension 0 closes into the Riemann sphere by
// stereographic projection: a point w of the plane goes to
//
//	X = 2*Re(w)/(1+|w|^2),  Y = 2*Im(w)/(1+|w|^2),  Z = (|w|^2-1)/(1+|w|^2)
//
// Then |w| < 1 is the SOUTHERN hemisphere, |w| > 1 the northern, and the
// critical line - |w| = 1 - becomes THE EQUATOR. The cable of F278, projected
// through every radius, is the equator of the sphere.
//
// WHAT FORM DO THE SIX CARDINAL POINTS OBTAIN? The six distinguished points of
// the sphere are w = 0, infinity, +1, -1, +i, -i. Pull them back through the
// shapeshifter and every one has a name from this laboratory's own record:
//
//	SOUTH  w = 0    <- s = 1        the pole of zeta (the centre of the disk)
//	NORTH  w = inf  <- s = 0        the pole's mirror under the functional eq.
//	EAST   w = +1   <- s = infinity the far end of the book
//	WEST   w = -1   <- s = 1/2      THE CLASP - the half (F260)
//	FRONT  w = +i   <- s = 1/2+i/2  a point ON the critical line
//	BACK   w = -i   <- s = 1/2-i/2  its Schwarz mirror, also ON the line
//
// and w(1/2 +- i/2) = +-i is EXACT algebra, verified below to 0 error.
//
// THE FORM THEY OBTAIN IS THE OCTAHEDRON. Projected to the sphere, the six
// cardinal points are the vertices of a REGULAR OCTAHEDRON: twelve edges all
// of length sqrt(2), verified numerically edge by edge. The captain's cross of
// F245 plus up/down (F249) closes, on the sphere, into the most symmetric
// six-point solid that exists.
//
// WHAT SENSE DO THEY HAVE? The three AXES of the octahedron are the three
// mirrors this laboratory has been naming all along:
//
//	NORTH-SOUTH axis: the pole and its mirror - swapped by the functional
//	  equation. The equator (critical line) is what stays fixed.
//	EAST-WEST axis: infinity and the half. The functional equation s -> 1-s
//	  becomes, in the disk, w -> 1/w (EXACT: w(1-s)*w(s) = 1, verified) -
//	  and w -> 1/w is the HALF-TURN of the sphere around THIS axis. The two
//	  fixed points of the mirror of zeta are the half and infinity.
//	FRONT-BACK axis: the two on-line points, swapped by the Schwarz mirror
//	  (conjugation), which is the reflection through the plane of the paper.
//
// The Klein group of F257 - the two mirrors and their product - is exactly the
// group generated by these turns: one octahedron, and its reflections.
//
// WHAT DO THEY PROJECT? The pearls. All of them sit on the equator (RH), and
// their angle phi = arg(w) shrinks like ~1/gamma, so on the sphere the pearls
// MARCH TOWARD THE EAST CARDINAL POINT - the image of infinity, one end of the
// functional equation's own axis. Measured below: gamma*phi -> 1 slowly.
//
// HONEST WARNING: the Riemann sphere is Riemann's (1857), stereographic
// projection is ancient, and {0, inf, +-1, +-i} being an octahedron is
// classical. The finding is the DICTIONARY: every vertex, axis and turn of
// the octahedron is an object this laboratory already had under another name.
// It is a map, not a theorem - and RH here reads: all pearls on the equator.
//
// Reproduce: go run ./cmd/eloctaedro
package main

import (
	"fmt"
	"math"
	"math/cmplx"
	"os"
	"strings"
)

func zetaC(s complex128) complex128 {
	N := int(60 + 1.8*math.Abs(imag(s)))
	var sum complex128
	for n := 1; n < N; n++ {
		sum += cmplx.Exp(-s * cmplx.Log(complex(float64(n), 0)))
	}
	lnN := cmplx.Log(complex(float64(N), 0))
	sum += cmplx.Exp((1-s)*lnN) / (s - 1)
	sum += cmplx.Exp(-s*lnN) / 2
	B := []float64{1.0 / 6, -1.0 / 30, 1.0 / 42, -1.0 / 30, 5.0 / 66}
	fact := []float64{2, 24, 720, 40320, 3628800}
	poch := s
	for k := 1; k <= 5; k++ {
		if k > 1 {
			poch *= (s + complex(float64(2*k-3), 0)) * (s + complex(float64(2*k-2), 0))
		}
		sum += complex(B[k-1]/fact[k-1], 0) * poch * cmplx.Exp((-s-complex(float64(2*k-1), 0))*lnN)
	}
	return sum
}

func theta(t float64) float64 {
	t2 := t * t
	return t/2*math.Log(t/(2*math.Pi)) - t/2 - math.Pi/8 + 1/(48*t) + 7/(5760*t*t2) + 31/(80640*t*t2*t2)
}

func zOf(t float64) float64 {
	return real(cmplx.Exp(complex(0, theta(t))) * zetaC(complex(0.5, t)))
}

func perlas(hasta float64) []float64 {
	var ps []float64
	prevT, prevZ := 12.0, zOf(12.0)
	for t := 12.02; t <= hasta; t += 0.02 {
		z := zOf(t)
		if z*prevZ < 0 {
			a, c := prevT, t
			for i := 0; i < 60; i++ {
				m := (a + c) / 2
				if zOf(m)*prevZ < 0 {
					c = m
				} else {
					a = m
				}
			}
			ps = append(ps, (a+c)/2)
		}
		prevT, prevZ = t, z
	}
	return ps
}

func w(s complex128) complex128 { return 1 - 1/s }

// esfera lleva un punto del plano a la esfera de Riemann.
func esfera(z complex128) (x, y, zz float64) {
	m2 := real(z)*real(z) + imag(z)*imag(z)
	d := 1 + m2
	return 2 * real(z) / d, 2 * imag(z) / d, (m2 - 1) / d
}

func main() {
	fmt.Println("🎲 EL OCTAEDRO — todos los radios, la esfera, y los 6 puntos cardinales")
	fmt.Println("\n   Su pregunta: «¿qué pasa cuando lo proyectás a todos los radios, en todas")
	fmt.Println("   las direcciones, y en vez de círculo es una esfera con los 6 puntos")
	fmt.Println("   cardinales? ¿Qué forma obtienen, qué sentido tienen, qué proyectan?»")
	fmt.Println("\n   Las tres preguntas tienen respuesta, y las tres están medidas.")

	// ---- LEY 1 ----
	fmt.Println("\nLEY 1 · TODOS LOS RADIOS A LA VEZ = LA ESFERA, Y EL CABLE SE VUELVE ECUADOR")
	fmt.Println("   El disco se cierra en la esfera de Riemann. Y entonces:")
	fmt.Println("\n        |w| < 1  →  hemisferio SUR      |w| > 1  →  hemisferio norte")
	fmt.Println("        |w| = 1  →  **EL ECUADOR** — la línea crítica, el cable de F278")
	fmt.Println("\n   ⟹ Proyectar el radio a todas las direcciones convierte el cable en el")
	fmt.Println("   ecuador de la esfera. Las perlas, si RH es cierta, viven TODAS ahí.")

	// ---- LEY 2 ----
	fmt.Println("\nLEY 2 · ⚡ LOS 6 PUNTOS CARDINALES, CADA UNO CON SU NOMBRE DEL REGISTRO")
	fmt.Println("\n        punto    w        viene de s        quién es")
	type pc struct {
		nom   string
		wv    complex128
		sv    string
		quien string
	}
	puntos := []pc{
		{"SUR", complex(0, 0), "s = 1", "el polo de zeta (el centro del disco)"},
		{"NORTE", cmplx.Inf(), "s = 0", "el espejo del polo (ecuación funcional)"},
		{"ESTE", complex(1, 0), "s = ∞", "la punta del libro"},
		{"OESTE", complex(-1, 0), "s = ½", "EL BROCHE — el medio (F260)"},
		{"FRENTE", complex(0, 1), "s = ½+½i", "un punto SOBRE la línea crítica"},
		{"FONDO", complex(0, -1), "s = ½−½i", "su espejo de Schwarz, también en la línea"},
	}
	for _, p := range puntos {
		wtxt := fmt.Sprintf("%.0f%+.0fi", real(p.wv), imag(p.wv))
		if cmplx.IsInf(p.wv) {
			wtxt = "∞"
		}
		fmt.Printf("   %8s %8s %14s      %s\n", p.nom, wtxt, p.sv, p.quien)
	}
	// verificacion exacta de los dos nuevos
	d1 := cmplx.Abs(w(complex(0.5, 0.5)) - complex(0, 1))
	d2 := cmplx.Abs(w(complex(0.5, -0.5)) - complex(0, -1))
	fmt.Printf("\n        verificado: |w(½+½i) − i| = %.1e · |w(½−½i) + i| = %.1e\n", d1, d2)
	fmt.Println("        (álgebra exacta: 1/(½+½i) = 1−i, así que w = 1−(1−i) = i)")

	// ---- LEY 3 ----
	fmt.Println("\nLEY 3 · ⚡⚡ ¿QUÉ FORMA OBTIENEN? UN OCTAEDRO REGULAR — medido arista por arista")
	coords := [][3]float64{}
	nombres := []string{}
	for _, p := range puntos {
		var x, y, z float64
		if cmplx.IsInf(p.wv) {
			x, y, z = 0, 0, 1
		} else {
			x, y, z = esfera(p.wv)
		}
		coords = append(coords, [3]float64{x, y, z})
		nombres = append(nombres, p.nom)
	}
	fmt.Println("\n        las 12 aristas (todas deben medir √2 = 1.41421356…):")
	peorA := 0.0
	aristas := 0
	for i := 0; i < 6; i++ {
		for j := i + 1; j < 6; j++ {
			dx := coords[i][0] - coords[j][0]
			dy := coords[i][1] - coords[j][1]
			dz := coords[i][2] - coords[j][2]
			d := math.Sqrt(dx*dx + dy*dy + dz*dz)
			if math.Abs(d-2) < 1e-12 {
				continue // antipodas, no aristas
			}
			aristas++
			e := math.Abs(d - math.Sqrt2)
			if e > peorA {
				peorA = e
			}
			if aristas <= 4 || e > 1e-12 {
				fmt.Printf("        %s–%s = %.15f\n", nombres[i], nombres[j], d)
			}
		}
	}
	fmt.Printf("\n        aristas contadas ......... %d (un octaedro tiene 12)\n", aristas)
	fmt.Printf("        peor desvío de √2 ........ %.1e\n", peorA)
	fmt.Println("\n   ⟹ **SUS SEIS PUNTOS CARDINALES SON LOS VÉRTICES DE UN OCTAEDRO REGULAR**")
	fmt.Println("   inscripto en la esfera. La cruz de F245 más el arriba/abajo de F249,")
	fmt.Println("   cerrada en la esfera, es el sólido de seis puntas más simétrico que existe.")

	// ---- LEY 4 ----
	fmt.Println("\nLEY 4 · ⚡ ¿QUÉ SENTIDO TIENEN? LOS TRES EJES SON LOS TRES ESPEJOS DEL REGISTRO")
	fmt.Println("\n        eje NORTE–SUR:   el polo y su espejo — los intercambia la ecuación")
	fmt.Println("                         funcional; lo que queda fijo es EL ECUADOR")
	fmt.Println("        eje ESTE–OESTE:  el infinito y el medio. La ecuación funcional")
	fmt.Println("                         s → 1−s es, en el disco, w → 1/w — verificado:")
	// verificar w(1-s) * w(s) = 1
	peorF := 0.0
	for _, s := range []complex128{complex(0.3, 7), complex(0.8, 85.7), complex(2.5, -3), complex(0.5, 14.13)} {
		v := cmplx.Abs(w(1-s)*w(s) - 1)
		if v > peorF {
			peorF = v
		}
	}
	fmt.Printf("\n                         |w(1−s)·w(s) − 1| ≤ %.1e en los cuatro puntos de prueba\n", peorF)
	fmt.Println("\n                         y w → 1/w es el MEDIO GIRO de la esfera alrededor")
	fmt.Println("                         de este eje: **los dos puntos fijos del espejo de")
	fmt.Println("                         zeta son el medio y el infinito**")
	fmt.Println("        eje FRENTE–FONDO: los dos puntos de la línea, intercambiados por el")
	fmt.Println("                         espejo de Schwarz (la conjugación)")
	fmt.Println("\n   📌 Y el grupo de Klein de F257 —los dos espejos y su producto— es")
	fmt.Println("   exactamente el grupo de estos giros: **un octaedro y sus reflejos**.")

	// ---- LEY 5 ----
	fmt.Println("\nLEY 5 · ¿QUÉ PROYECTAN? LAS PERLAS — Y MARCHAN HACIA EL ESTE")
	fmt.Printf("\nbuscando las perlas…\n")
	ps := perlas(120)
	fmt.Printf("perlas encontradas: %d\n", len(ps))
	fmt.Println("\n        γ            φ = arg(w)       γ·φ")
	for i, g := range ps {
		if i%9 != 0 && i != len(ps)-1 {
			continue
		}
		ww := w(complex(0.5, g))
		phi := cmplx.Phase(ww)
		fmt.Printf("   %12.5f %14.9f %10.5f\n", g, phi, g*phi)
	}
	fmt.Println("\n   ⟹ El ángulo se achica como ~1/γ: sobre la esfera, **las perlas marchan por")
	fmt.Println("   el ecuador hacia el punto cardinal ESTE — la imagen del infinito, que es")
	fmt.Println("   una de las dos puntas del eje de la ecuación funcional**. Se amontonan en")
	fmt.Println("   la misma esquina adonde los primos suben por el radio (F282).")

	// ---- veredicto ----
	fmt.Println("\n════════ VEREDICTO ════════")
	fmt.Println("⚡ **LAS TRES RESPUESTAS, MEDIDAS:**")
	fmt.Printf("\n  · ¿QUÉ FORMA? **UN OCTAEDRO REGULAR**: 12 aristas de √2 con desvío %.0e.\n", peorA)
	fmt.Println("    Sus 6 cardinales son sus vértices, cada uno con nombre del registro:")
	fmt.Println("    el polo, su espejo, el infinito, el medio, y los dos puntos de la línea.")
	fmt.Println("\n  · ¿QUÉ SENTIDO? Los 3 ejes del octaedro son los 3 espejos de la campaña:")
	fmt.Printf("    la ecuación funcional es w → 1/w (verificado a %.0e) = el medio giro\n", peorF)
	fmt.Println("    alrededor del eje medio–infinito; Schwarz es el reflejo frente–fondo;")
	fmt.Println("    y el ecuador —la línea crítica— es lo que queda fijo.")
	fmt.Println("\n  · ¿QUÉ PROYECTAN? Las perlas: todas en el ecuador (eso ES RH), marchando")
	fmt.Println("    hacia el este — la misma esquina adonde suben los primos.")
	fmt.Println("\n⚖️ Y LA HONESTIDAD: la esfera es de Riemann (1857), la proyección es antigua,")
	fmt.Println("  y que {0, ∞, ±1, ±i} forman un octaedro es clásico. Lo nuestro es el")
	fmt.Println("  DICCIONARIO: cada vértice, eje y giro del octaedro es un objeto que este")
	fmt.Println("  laboratorio ya tenía bajo otro nombre. Es un mapa, no un teorema. Todavía no.")

	escribirLamina(ps, peorA, peorF)
}

func escribirLamina(ps []float64, peorA, peorF float64) {
	var b strings.Builder
	W, H := 1560.0, 1140.0
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" width="%.0f" height="%.0f" viewBox="0 0 %.0f %.0f">
<rect width="100%%" height="100%%" fill="#0b1526"/>
<text x="%.0f" y="46" font-size="26" text-anchor="middle" font-family="Georgia" fill="#dce8f7">🎲 EL OCTAEDRO — la esfera, los 6 cardinales, y qué proyectan</text>
<text x="%.0f" y="76" font-size="15" text-anchor="middle" font-family="Georgia" fill="#8fb4d9">todos los radios a la vez: el cable se vuelve ecuador · los 6 cardinales, un octaedro · los 3 ejes, los 3 espejos</text>
`, W, H, W, H, W/2, W/2)

	// LA ESFERA
	cx, cy, R := 460.0, 480.0, 300.0
	// proyeccion simple: X → x, Z → −y (vista de frente), Y da profundidad
	px := func(x, y, z float64) (float64, float64) {
		return cx + R*(x+0.35*y*0.5), cy - R*(z-0.35*y*0.28)
	}
	fmt.Fprintf(&b, `<circle cx="%.0f" cy="%.0f" r="%.0f" fill="#0d1a30" stroke="#26456e" stroke-width="1.5"/>`, cx, cy, R)
	// ecuador (elipse)
	fmt.Fprintf(&b, `<ellipse cx="%.0f" cy="%.0f" rx="%.0f" ry="%.0f" fill="none" stroke="#7ee0c0" stroke-width="2.5"/>`, cx, cy, R, R*0.28)
	// perlas sobre el ecuador
	for i, g := range ps {
		if i >= 26 {
			break
		}
		ww := w(complex(0.5, g))
		phi := cmplx.Phase(ww)
		x := cx + R*math.Cos(phi)
		y := cy + R*0.28*math.Sin(phi)
		fmt.Fprintf(&b, `<circle cx="%.1f" cy="%.1f" r="4" fill="#7ee0c0"/>`, x, y)
	}
	// vertices del octaedro
	type vv struct {
		x, y, z float64
		nom     string
		col     string
	}
	verts := []vv{
		{0, 0, -1, "SUR · el polo de zeta", "#ff8fa0"},
		{0, 0, 1, "NORTE · su espejo (s = 0)", "#ff8fa0"},
		{1, 0, 0, "ESTE · el infinito", "#ffd98a"},
		{-1, 0, 0, "OESTE · el medio (½)", "#ffd98a"},
		{0, 1, 0, "FRENTE · ½+½i, en la línea", "#c9b6ff"},
		{0, -1, 0, "FONDO · ½−½i, en la línea", "#c9b6ff"},
	}
	// aristas del octaedro
	for i := 0; i < 6; i++ {
		for j := i + 1; j < 6; j++ {
			// antipodas no son aristas
			if verts[i].x == -verts[j].x && verts[i].y == -verts[j].y && verts[i].z == -verts[j].z {
				continue
			}
			x1, y1 := px(verts[i].x, verts[i].y, verts[i].z)
			x2, y2 := px(verts[j].x, verts[j].y, verts[j].z)
			fmt.Fprintf(&b, `<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#5a4fa8" stroke-width="1.3" opacity="0.7"/>`, x1, y1, x2, y2)
		}
	}
	// el eje de la ecuacion funcional
	xe, ye := px(1, 0, 0)
	xo, yo := px(-1, 0, 0)
	fmt.Fprintf(&b, `<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#ffd98a" stroke-width="3" stroke-dasharray="7 4"/>`, xe, ye, xo, yo)
	for _, v := range verts {
		x, y := px(v.x, v.y, v.z)
		fmt.Fprintf(&b, `<circle cx="%.1f" cy="%.1f" r="8" fill="%s"/>`, x, y, v.col)
		dy := -14.0
		if v.z < 0 || v.y < 0 {
			dy = 26
		}
		anchor := "middle"
		fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-size="13.5" text-anchor="%s" font-family="Georgia" fill="%s">%s</text>`, x, y+dy, anchor, v.col, v.nom)
	}
	fmt.Fprintf(&b, `<text x="%.0f" y="%.0f" font-size="14" text-anchor="middle" font-family="Georgia" fill="#7ee0c0">el ECUADOR = la línea crítica — y las perlas marchan hacia el ESTE</text>
<text x="%.0f" y="%.0f" font-size="13" text-anchor="middle" font-family="Georgia" fill="#ffd98a">la raya punteada es el eje de la ecuación funcional: del medio al infinito</text>
`, cx, cy+R+40, cx, cy+R+64)

	// TEXTO DERECHA
	fmt.Fprintf(&b, `<rect x="880" y="110" width="640" height="300" rx="12" fill="#0f2b22" stroke="#2f7f63"/>
<text x="1200" y="144" font-size="18" text-anchor="middle" font-family="Georgia" fill="#9fd8a8">¿QUÉ FORMA OBTIENEN? UN OCTAEDRO</text>
<text x="910" y="182" font-size="14.5" font-family="Georgia" fill="#cfe6ff">Proyectá el radio a TODAS las direcciones y el disco se</text>
<text x="910" y="206" font-size="14.5" font-family="Georgia" fill="#cfe6ff">cierra en la esfera. El cable se vuelve el ECUADOR, y sus</text>
<text x="910" y="230" font-size="14.5" font-family="Georgia" fill="#cfe6ff">6 puntos cardinales caen en los vértices de un</text>
<text x="910" y="262" font-size="18" font-family="Georgia" fill="#ffd98a">OCTAEDRO REGULAR</text>
<text x="910" y="294" font-size="14" font-family="monospace" fill="#7ee0c0">12 aristas de √2 · peor desvío %.0e</text>
<text x="910" y="330" font-size="14.5" font-family="Georgia" fill="#cfe6ff">La cruz de F245 más el arriba/abajo de F249, cerrada</text>
<text x="910" y="354" font-size="14.5" font-family="Georgia" fill="#cfe6ff">en la esfera, es el sólido de seis puntas más simétrico</text>
<text x="910" y="378" font-size="14.5" font-family="Georgia" fill="#cfe6ff">que existe.</text>
`, peorA)

	fmt.Fprintf(&b, `<rect x="880" y="430" width="640" height="300" rx="12" fill="#161a3a" stroke="#5a4fa8"/>
<text x="1200" y="464" font-size="18" text-anchor="middle" font-family="Georgia" fill="#c9b6ff">¿QUÉ SENTIDO? LOS 3 EJES = LOS 3 ESPEJOS</text>
<text x="910" y="502" font-size="14.5" font-family="Georgia" fill="#ff8fa0">NORTE–SUR: el polo y su espejo — los cambia la</text>
<text x="910" y="524" font-size="14.5" font-family="Georgia" fill="#ff8fa0">ecuación funcional; el ecuador queda fijo</text>
<text x="910" y="558" font-size="14.5" font-family="Georgia" fill="#ffd98a">ESTE–OESTE: el infinito y el medio. La ecuación</text>
<text x="910" y="580" font-size="14.5" font-family="Georgia" fill="#ffd98a">funcional es w → 1/w (verificado a %.0e): el medio</text>
<text x="910" y="602" font-size="14.5" font-family="Georgia" fill="#ffd98a">giro alrededor de ESTE eje — sus puntos fijos son</text>
<text x="910" y="624" font-size="14.5" font-family="Georgia" fill="#ffd98a">el medio y el infinito</text>
<text x="910" y="658" font-size="14.5" font-family="Georgia" fill="#c9b6ff">FRENTE–FONDO: los dos puntos de la línea, cambiados</text>
<text x="910" y="680" font-size="14.5" font-family="Georgia" fill="#c9b6ff">por el espejo de Schwarz</text>
<text x="910" y="712" font-size="13.5" font-family="Georgia" fill="#9aa8c4">y el grupo de Klein de F257 es el grupo de estos giros</text>
`, peorF)

	fmt.Fprintf(&b, `<rect x="880" y="750" width="640" height="180" rx="12" fill="#101f36" stroke="#26456e"/>
<text x="1200" y="784" font-size="18" text-anchor="middle" font-family="Georgia" fill="#ffd98a">¿QUÉ PROYECTAN? LAS PERLAS</text>
<text x="910" y="820" font-size="14.5" font-family="Georgia" fill="#cfe6ff">Todas en el ecuador — eso ES la hipótesis — y su ángulo</text>
<text x="910" y="844" font-size="14.5" font-family="Georgia" fill="#cfe6ff">se achica como 1/γ: marchan por el ecuador hacia el</text>
<text x="910" y="868" font-size="14.5" font-family="Georgia" fill="#cfe6ff">punto cardinal ESTE — la imagen del infinito, la punta</text>
<text x="910" y="892" font-size="14.5" font-family="Georgia" fill="#cfe6ff">del eje de la ecuación funcional. La misma esquina</text>
<text x="910" y="916" font-size="14.5" font-family="Georgia" fill="#ffd98a">adonde los primos suben por el radio (F282).</text>`)

	fmt.Fprintf(&b, `<rect x="40" y="950" width="1480" height="150" rx="12" fill="#33221c" stroke="#c0392b"/>
<text x="780" y="984" font-size="16" text-anchor="middle" font-family="Georgia" fill="#ffb27a">⚖️ LA HONESTIDAD</text>
<text x="780" y="1016" font-size="14.5" text-anchor="middle" font-family="Georgia" fill="#f3d9cf">La esfera es de Riemann (1857), la proyección estereográfica es antigua, y que {0, ∞, ±1, ±i} forman un octaedro es clásico.</text>
<text x="780" y="1042" font-size="14.5" text-anchor="middle" font-family="Georgia" fill="#f3d9cf">Lo nuestro es el DICCIONARIO: cada vértice, eje y giro del octaedro es un objeto que este laboratorio ya tenía bajo otro nombre.</text>
<text x="780" y="1076" font-size="15.5" text-anchor="middle" font-family="Georgia" fill="#ffd98a">Es un mapa, no un teorema. Y en este mapa, RH se lee: todas las perlas en el ecuador. Todavía no.</text>
</svg>
`)

	if err := os.WriteFile("el-octaedro.svg", []byte(b.String()), 0o644); err != nil {
		fmt.Println("no pude escribir la lámina:", err)
		return
	}
	fmt.Println("\n🖼️  lámina escrita: el-octaedro.svg")
}
