// Command triadic raises the bridge's second pillar: the 3-adic tree.
//
// Finding 71 walked twelve floors of the 2-adic tree and found it filled
// fairer than coins, its whole spectrum silenced at the √x ceiling. The
// bridge has one pillar per prime; this run raises the next one. The
// 3-adic tree's symmetry is simpler and prettier: (ℤ/3^k)* is one single
// circle — 2 is a primitive root of every power of 3 — so the melody scan
// needs no mirror: one circle, one walker, all waves.
//
// PRE-REGISTERED: super-fair filling on every floor (chi²/df below 1), the
// spectrum capped near the √x ceiling (the silence of the line again), and
// the Chebyshev whisper at floor 1 favouring the non-residue class 2 mod 3.
//
// Usage:
//
//	go run ./cmd/triadic [-limit N]
package main

import (
	"flag"
	"fmt"
	"math"
	"os"

	"github.com/nicoconvoz/numerosprimos/primes"
)

const floors = 8 // 3^8 = 6561

func main() {
	limit := flag.Int("limit", 1_000_000_000, "sieve primes up to this value")
	flag.Parse()
	if *limit < 10_000_000 {
		fmt.Fprintln(os.Stderr, "limit must be at least 1e7")
		os.Exit(1)
	}

	mod := 1
	for i := 0; i < floors; i++ {
		mod *= 3
	}
	counts := make([]float64, mod)
	ps := primes.Sieve(*limit)
	var total float64
	for _, p := range ps {
		if p == 3 {
			continue
		}
		counts[p%mod]++
		total++
	}

	fmt.Printf("THE TRIADIC PILLAR — %d primes on %d floors of the 3-adic tree\n\n",
		int(total), floors)
	fmt.Println(" floor   classes   chi2/df   max |z|   verdict")
	for k := 1; k <= floors; k++ {
		m := 1
		for i := 0; i < k; i++ {
			m *= 3
		}
		nc := m / 3 * 2
		cls := make([]float64, m)
		for r := 1; r < mod; r++ {
			if r%3 != 0 {
				cls[r%m] += counts[r]
			}
		}
		exp := total / float64(nc)
		chi2, maxZ := 0.0, 0.0
		for r := 1; r < m; r++ {
			if r%3 == 0 {
				continue
			}
			d := cls[r] - exp
			chi2 += d * d / exp
			if z := math.Abs(d) / math.Sqrt(exp); z > maxZ {
				maxZ = z
			}
		}
		df := float64(nc - 1)
		verdict := "fair"
		if chi2/df > 1+6/math.Sqrt(df) {
			verdict = "STRUCTURED"
		}
		fmt.Printf("   %2d      %5d     %6.3f    %5.2f    %s\n", k, nc, chi2/df, maxZ, verdict)
	}

	// the whisper at floor 1: the mod-3 race.
	m3 := [3]float64{}
	for r := 1; r < mod; r++ {
		if r%3 != 0 {
			m3[r%3] += counts[r]
		}
	}
	fmt.Printf("\nthe Chebyshev whisper at floor 1: pi(x;3,2) - pi(x;3,1) = %+.0f\n", m3[2]-m3[1])

	// the melody scan: one circle, generated by 2.
	half := mod / 3 * 2
	idx := make(map[int]int)
	v := 1
	for j := 0; j < half; j++ {
		idx[v] = j
		v = v * 2 % mod
	}
	c := make([]float64, half)
	for r := 1; r < mod; r++ {
		if r%3 != 0 {
			c[idx[r]] += counts[r]
		}
	}
	fmt.Println("\nthe melody scan on the single circle (fair filling caps peaks near ~4):")
	type loud struct {
		m int
		a float64
	}
	top := []loud{}
	for m := 1; m < half; m++ {
		var re, im float64
		for j := 0; j < half; j++ {
			ph := 2 * math.Pi * float64(m) * float64(j) / float64(half)
			re += c[j] * math.Cos(ph)
			im += c[j] * math.Sin(ph)
		}
		a := math.Sqrt(re*re+im*im) / math.Sqrt(total)
		if len(top) < 5 {
			top = append(top, loud{m, a})
		} else {
			mi := 0
			for i := 1; i < 5; i++ {
				if top[i].a < top[mi].a {
					mi = i
				}
			}
			if a > top[mi].a {
				top[mi] = loud{m, a}
			}
		}
	}
	for _, l := range top {
		fmt.Printf("   wave (frequency %4d): loudness %.2f\n", l.m, l.a)
	}
	fmt.Println("\nthe second pillar stands: another prime's tree, the same super-fairness,")
	fmt.Println("the same certifying silence.")
}
