package primes

// From returns the entries of seq that are at least min, as a fresh slice.
//
// Residue analysis modulo m is only defined for primes above m: 2 and 3 are the
// primes that generate the mod-3 structure, and a rule generated by them cannot
// bind them. Every measurement of the residue walk must drop them first, and
// mixing runs that do with runs that do not silently invalidates comparisons.
func From(seq []int, min int) []int {
	out := make([]int, 0, len(seq))
	for _, p := range seq {
		if p >= min {
			out = append(out, p)
		}
	}
	return out
}

// Flips marks which gaps move the residue and which leave it where it was.
//
// A gap divisible by modulus keeps the residue (0); any other gap changes it
// (1). Discarding the gap's value and keeping only this bit reduces the
// sequence to its form: whether a step moved, not how far.
//
// A modulus below 2 yields an empty slice.
func Flips(gaps []int, modulus int) []int {
	if modulus < 2 {
		return []int{}
	}

	out := make([]int, len(gaps))
	for i, g := range gaps {
		if g%modulus != 0 {
			out[i] = 1
		}
	}

	return out
}

// TransitionMatrix counts the residue steps between consecutive entries of seq.
//
// The result is indexed [from][to] over residues modulo m. An unbiased sequence
// would spread its mass evenly; real primes concentrate off the diagonal,
// because consecutive primes avoid repeating their residue class.
//
// A modulus below 2 yields nil.
func TransitionMatrix(seq []int, modulus int) [][]int {
	if modulus < 2 {
		return nil
	}

	out := make([][]int, modulus)
	for i := range out {
		out[i] = make([]int, modulus)
	}
	for i := 0; i+1 < len(seq); i++ {
		out[seq[i]%modulus][seq[i+1]%modulus]++
	}

	return out
}
